### ISSUE TITLE
OS X issue

### ISSUE THREAD

**Issue by soulfly** [spicavigo/kafka-rust#11]
Hi there, 

I have Kafka in my dependencies

    [dependencies]
    kafka = "0.1.6"

then I added 

    extern crate kafka;

then do 'cargo build'

and receive this big error log:

    error: linking with `cc` failed: exit code: 1
    note: "cc" "-m64" "-L" "/usr/local/lib/rustlib/x86_64-apple-darwin/lib" "-o" "
    ....
    note: ld: warning: directory not found for option '-L/Users/igor/kafka-pipe/kafka-pipe/.rust/lib/x86_64- apple-darwin'
    ld: warning: directory not found for option '-L/Users/igor/kafka-pipe/kafka-pipe/lib/x86_64-apple-darwin'
    ld: library not found for -lsnappy
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

    error: aborting due to previous error 
    Could not compile `kafka-pipe`

**Comment by soulfly** [comment]
Okay

    brew install snappy

did a magic

**Comment by motazreda** [comment]
still the same problem

**Comment by xitep** [comment]
@motazreda can you describe your setup a little bit? where is your native snappy lib installed? which version of `kafka-rust` are you having the problem with? Recent versions support setting the `LD_LIBRARY_PATH` and `LD_RUN_PATH`:

```
# in short, the directory where libsnappy.a is located
export LD_LIBRARY_PATH=/foo/bar/snappy/lib
export LD_RUN_PATH=$LD_LIBRARY_PATH
...
cargo build
```
