### ISSUE TITLE
client/consumer/producer: time api

### ISSUE THREAD

**Issue by xitep** [spicavigo/kafka-rust#115]
Rework the public API such that it accepts `std::time::Duration` in places where it currently expects the user to provide a duration in milliseconds. This will be less prone to unit mismatches and errors by mistake. So far the places identified are:

* `kafka::producer::Builder::with_ack_timeout`
* `kafka::client::KafkaClient::produce_messages` (ack_timeout parameter)
* `kafka::client::KafkaClient::set_retry_backoff_time` and `kafka::client::KafkaClient::retry_backoff_time`
* `kafka::client::KafkaClient::fetch_max_wait_time` and `kafka::client::KafkaClient::set_fetch_max_wait_time`
* `kafka::consumer::Builder::with_fetch_max_wait_time`

Since `const_fn` is not stable yet (and `Duration` constructor functions are not `const`), we'll keep the type of the following but rename them for sake of clarity:

* `kafka::producer::DEFAULT_ACK_TIMEOUT` -> `DEFAULT_ACK_TIMEOUT_MILLIS`
* `kafka::client::DEFAULT_RETRY_BACKOFF_TIME` -> `DEFAULT_RETRY_BACKOFF_TIME_MILLIS`
* `kafka::client::DEFAULT_FETCH_MAX_WAIT_TIME` -> `DEFAULT_FETCH_MAX_WAIT_TIME_MILLIS`

Internally, we might persist the values as milliseconds if necessary to avoid repeated unnecessary conversions from the duration representation. However, the conversion of a `Duration` to an `i32` (as often required by the kafka protocol) might fail; we shall introduce an `InvalidDuration` error  (ideally with some information about which duration was found to be invalid) and fail if the conversion is not safely possible: For `Producer` and `Consumer` we would fail upon the call to their `Builder::create()` method. In `KafkaClient` we'll be failing lazily in `fetch_message` and `produce_messages`.

This will be a breaking change of course.

All new, future public API aspects around a duration shall be represented with the information being exposed as a `std::time::Duration`.

**Comment by Hoverbear** [comment]
@xitep Could:

`kafka::producer::DEFAULT_ACK_TIMEOUT` -> `DEFAULT_ACK_TIMEOUT_MILLIS`
`kafka::client::DEFAULT_RETRY_BACKOFF_TIME` -> `DEFAULT_RETRY_BACKOFF_TIME_MILLIS`
`kafka::client::DEFAULT_FETCH_MAX_WAIT_TIME` -> DEFAULT_FETCH_MAX_WAIT_TIME_MILLIS`

Be handled with lazy statics?

**Comment by xitep** [comment]
@Hoverbear that's a good idea! thanks for the hint, i'll try that out.

**Comment by xitep** [comment]
it looks like #102 will be merged sooner than this ticket, therefore, the newly added elements from #102 shall be renamed as outlined in this ticket; these new newly added elements are (or will be):

* `kafka::client::DEFAULT_CONN_IDLE_TIMEOUT`
* `kafka::client::KafkaClient::set_connection_idle_timeout` and `kafka::client::KafkaClient::connection_idle_timeout`
* `kafka::producer::Builder::with_connection_idle_timeout`
* `kafka::consumer::Builder::with_connection_idle_timeout`

**Comment by xitep** [comment]
@Hoverbear just some feedback on the `lazy_static` approach; it works, but i'm not really satisfied with the resulting api. first, the "constants" need to be de-referenced explicitly. secondly, in the generated documentation they show up in a different section than the rest of the constant.

i'll go with the originally proposed re-naming then. anyway, many thanks for the idea!

**Comment by Hoverbear** [comment]
Aww oh well. :)

**Comment by xitep** [comment]
Published on [crates.io](https://crates.io/crates/kafka/0.5.0) as 0.5.0
