### ISSUE TITLE
Consider using rust-snappy

### ISSUE THREAD

**Issue by craftytrickster** [spicavigo/kafka-rust#116]
There is a pure rust implementation of snappy https://github.com/BurntSushi/rust-snappy that perhaps could replace the need to use `libsnappy-dev`.

**Comment by xitep** [comment]
Thanks for the ticket! Exactly what I was thinking about when seeing the news this morning! Just for reference, a related ticket is/was #49.

**Comment by craftytrickster** [comment]
You know what they say, great minds think alike.

**Comment by xitep** [comment]
Resolved by #148; will close this issue once 0.6 is pushed to crates.io.

**Comment by xitep** [comment]
published on [crates.io](https://crates.io/crates/kafka/0.6.0)
