### ISSUE TITLE
Use latest rust-openssl

### ISSUE THREAD

**Issue by jedisct1** [spicavigo/kafka-rust#122]
It would be nice to upgrade to rust-openssl 0.8.x (current stable branch) in order to avoid conflicts with other crates linking openssl 0.8.

**Comment by xitep** [comment]
sounds good to me! have you got time to give this a try? i fear i might not be able to get my hands wet on this during this week.

**Comment by xitep** [comment]
fixed in master; will be released as part of the next 0.6 version on crates.io (still not sure when this happens), until then i'm keeping this open.

**Comment by hh9527** [comment]
rust-openssl 0.9.x has a better build-script in windows, why not upgrade directly to 0.9.x?

**Comment by xitep** [comment]
@hh9527 feel free to submit a PR

**Comment by hh9527** [comment]
@xitep Sorry, I am in restricted region, and can not give a PR. There is a diff patch to support openssl-0.9

This change will cause a break change for SSL. Example:
```rust
extern crate openssl;
extern crate kafka;

use openssl::ssl::{SslMethod, SslConnectorBuilder};
use std::io::{Read, Write};
use std::net::TcpStream;
use kafka::client::{KafkaClient, SecurityConfig};

fn main() {
    let connector = SslConnectorBuilder::new(SslMethod::tls()).unwrap().build();
    let mut client = KafkaClient::new_secure(vec!("localhost:9092".to_owned()),
                                             SecurityConfig::new(connector));
    client.load_metadata_all().unwrap();
}
```

[support-openssl-0.9.diff.txt](https://github.com/spicavigo/kafka-rust/files/593708/support-openssl-0.9.diff.txt)

**Comment by hh9527** [comment]
ping @xitep, is this patch OK

**Comment by xitep** [comment]
@hh9527 unfortunately, i don't have much time for this. with your patch applied, `cargo test` fails for me due to an example no being up-to-date. further, `cargo build --no-default-features` fails as well. may i ask you to look into this?

**Comment by hh9527** [comment]
@xitep I will try to give a PR after I installed MSVC in my personal laptop next week and fix that, but I am not sure...

**Comment by xitep** [comment]
Thanks you @flier we've got upgraded to 0.9. Will keep this ticket open until 0.6 get published to crates.io.

**Comment by xitep** [comment]
just published on [crates.io](https://crates.io/crates/kafka/0.6.0); closing this ticket. many thanks @flier! 👍

**Comment by dead10ck** [comment]
Thanks @flier !! :)
