### ISSUE TITLE
SipHasher has been deprecated

### ISSUE THREAD

**Issue by dead10ck** [spicavigo/kafka-rust#145]
[`SipHasher`](https://doc.rust-lang.org/std/hash/struct.SipHasher.html) has been deprecated in favor of [`DefaultHasher`](https://doc.rust-lang.org/std/collections/hash_map/struct.DefaultHasher.html), but `DefaultHasher` says

> The internal algorithm is not specified, and so it and its hashes should not be relied upon over releases.

We need to use a stable hashing algorithm to avoid surprises with data distribution.

**Comment by xitep** [comment]
just for reference; the `KafkaProducer` part of the official kafka distribution uses a [32bit murmur2 hash](https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/producer/internals/DefaultPartitioner.java#L69) by default.

**Comment by xitep** [comment]
Resolve, but will keep this open until 0.6 is pushed to crates.io.

**Comment by xitep** [comment]
@dead10ck i saw [your comment](https://github.com/spicavigo/kafka-rust/pull/151#pullrequestreview-35267233) about preferring the same hash algorithm as the official java clients, i.e. 32bit murmur2. i have to agree that this would make the best default. on the other hand, it appears that [sarama](https://github.com/Shopify/sarama), the golang kafka client, uses FNV-1 by default. i haven't checked other clients, but it appears to me that in the landscape of kafka, if users do care about message distribution consistency across their applications they simply have to explicitly specify their partitioner (and hashing algorithm).

do you want to set-up a new ticket for switching the default hashing algorithm to murmur2 32bit?

**Comment by dead10ck** [comment]
No, I'm not sure it's a big deal. I think this will be fine.

**Comment by xitep** [comment]
just published on [crates.io](https://crates.io/crates/kafka/0.6.0); closing this ticket.
