### ISSUE TITLE
dnscrypt client is not working if original DNS server is non-recursive

### ISSUE THREAD

**Issue by fred-chen** [spicavigo/kafka-rust#16]
The following function in "check-hijacking.sh" will never succeed if the original DNS server is working with non-recursive mode. That causes dnscrypt client in "standby" mode.

try_resolution() {
  exec alarmer 5 dig +tries=2 +time=3 +short google-public-dns-a.google.com \
    | egrep '^8[.]8[.]8[.]8' > /dev/null 2>&1
}

**Comment by xitep** [comment]
wrong project?
