### ISSUE TITLE
mismatched types with KafkaClient::new

### ISSUE THREAD

**Issue by soulfly** [spicavigo/kafka-rust#18]
Hi there, 

I have just copied your example

     let kafka_client = KafkaClient::new(&vec!("localhost:9092".to_string()));

and got the following error

    src/main.rs:48:45: 48:80 error: mismatched types:
     expected `collections::vec::Vec<collections::string::String>`,
     found `&collections::vec::Vec<collections::string::String>`
     (expected struct `collections::vec::Vec`,
     found &-ptr) [E0308]

Could you provide a working example and/or update the README file

**Comment by soulfly** [comment]
Ok, looks like I have to remove '&' and now it works

Please update the README file

**Comment by spicavigo** [comment]
Fixed https://github.com/spicavigo/kafka-rust/commit/c20e2d91f464b1509262c620f59e550bca481bce
