### ISSUE TITLE
Clarify ownership in API / Avoid needless allocations

### ISSUE THREAD

**Issue by xitep** [spicavigo/kafka-rust#19]
Hello ...

with ... edec13c *Removed references from struct methods since they want the ownership of objects anyway* ... the API has changed to "swallow" host and topic names. Was there a particular reason for doing so? If i understand it correctly, this is consistent with various client input/output structures (e.g. `util::ProduceMessage`).

However, the fact that the API "swallows" topics as `String`s requires clients to clone them on their input side (for repeated calls of the corresponding methods); Further, the fact that "topics" are a `String` in the output structures, implies repeated allocations even though very often the topic will vary little. This seems needless given that the client maintains an already allocated map of topics internally (which could be reused.)

Are we open to changes that would break the current client API?

**Comment by spicavigo** [comment]
I would like nothing more than to not "swallow" things up. I moved from reference to outright ownership for consistency reasons. I have been meaning to find sometime to have another shot at it but unfortunately couldn't.

Will welcome a PR on this

**Comment by xitep** [comment]
Most of the work is already prepared in the (not yet released) `branch-0.2.x`. I'm OK with the API in this branch regarding the issue reported here. (I still have some more changes to the API planned but rather for performance reasons regarding fetching messages.) I'm closing this one.
