### ISSUE TITLE
Regression causing lost messages

### ISSUE THREAD

**Issue by jedisct1** [spicavigo/kafka-rust#24]
Change 62535d6a762e638d8c815b773f9d6e1b10539108 introduced a serious regression.

The first message for a given topic is now always lost.

```rust
    let m1 = "a".to_owned().into_bytes();
    let m2 = "b".to_owned().into_bytes();
    let m3 = "c".to_owned().into_bytes();
    let req = vec!(utils::ProduceMessage{topic: "test".to_owned(), message: m1},
                   utils::ProduceMessage{topic: "test".to_owned(), message: m2},
                   utils::ProduceMessage{topic: "test".to_owned(), message: m3}
                   );
    client.send_messages(1, 100, req);
```

=> Only `m2` and `m3` are sent, `m1` is ignored.

I'd suggest reverting this change.

**Comment by xitep** [comment]
interesting! testing this on a channel with more than one partition i cannot observe this. however, on a topic with a single partition it really happens. will try to come up with a fix as soon as possible.

**Comment by xitep** [comment]
@jedisct1 thanks for reporting this. PR #25 should be fixing the issue. sorry for the troubles.

**Comment by xitep** [comment]
@jedisct1 can you confirm this issue is fixed for you?

**Comment by jedisct1** [comment]
The change looks fine, but I haven't tested it yet.

To be safe, I reverted 62535d6 in the version we run in production, but I will try this change shortly.

**Comment by spicavigo** [comment]
@jedisct1 Can we close this issue now?

**Comment by jedisct1** [comment]
Yes.

**Comment by xitep** [comment]
@jedisct1 many thanks for the confirmation
