### ISSUE TITLE
library not found for -lsnappy on OS X El Capitan

### ISSUE THREAD

**Issue by soulfly** [spicavigo/kafka-rust#27]
Just updated to OS X El Capitan and can't use your library

     cargo build

returns

    ld: library not found for -lsnappy

here is the output from homebrew:

    Igors-MacBook-Pro: igorkhomenko$ brew install snappy
    Warning: snappy-1.1.3 already installed
    Warning: You are using OS X 10.11.
    We do not provide support for this pre-release version.
    You may encounter build failures or other breakage.

**Comment by jedisct1** [comment]
`brew link snappy` maybe?

**Comment by soulfly** [comment]
Igors-MacBook-Pro: igorkhomenko$ brew link snappy
    Warning: Already linked: /usr/local/Cellar/snappy/1.1.3
    To relink: brew unlink snappy && brew link snappy

**Comment by rigdent** [comment]
I was able to get it to work by setting the library path
`export LIBRARY_PATH="/usr/local/lib"`
