### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by erickt** [spicavigo/kafka-rust#50]
Kafka has support for SSL in [KAFKA-1684](https://issues.apache.org/jira/browse/KAFKA-1684), so it'd be nice to support it here as well. Hyper supports SSL channels, so it's [implementation](https://github.com/hyperium/hyper/blob/master/src/net.rs) would be a useful reference.

**Comment by xitep** [comment]
many thanks to @Hoverbear for the initiative and the implementation! i'm keeping this ticket open until it is released on crates.io.

@erickt  feel free to test the `master` branch and provide feedback :)

**Comment by xitep** [comment]
released on crates.io as 0.3.1.
