### ISSUE TITLE
Producer performance

### ISSUE THREAD

**Issue by ihrwein** [spicavigo/kafka-rust#56]
This library is very promising :) Did you do any performance comparison with the official Kafka client library?

**Comment by xitep** [comment]
hello, just a very quick reply.

comparing kafka-rust with the official (java and scala) kafka client will lead to a very bad results. kafka-rust is not thread-safe (yet) unlike the java based implementations. this limits kafka-rust's performance heavily on the throughput it can achieve in real-world scenarios.

personally, i want to drive kafka-rust into a direction where it can be as good as the java client or even outperform it. however, there's still a long way to go.

**Comment by ihrwein** [comment]
Thanks for the quick reply, it was very informative :)

I will look at your code when I have time, this is a very interesting topic :)
