### ISSUE TITLE
producer: ensure distributing messages with the same key to the same partition

### ISSUE THREAD

**Issue by xitep** [spicavigo/kafka-rust#78]
The "key" - if available - of a message is typically used to derive a consistent partition which a message should be delivered to. Usually one computes a hash code of the key and maps that consistently on one of the partitions of the topic.

Clients of the `Producer` API can achieve this already by supplying a custom `Partitioner` to the `Producer`. However, we shall make this the standard behaviour of the `DefaultPartitioner`.

Unfortunately, topic metadata held by the `Producer` (which is supplied by `KafkaClient`) deliver only "available" partitions, which makes it impossible to implement the "consistency" aspect of the requirement. Therefore, this will require an extension to `KafkaClient` as well.

Regarding the hash algorithm we don't need a cryptographic hash function. However, we need to use one which doesn't different depending the platform - this rules out farmhash for example. (it seems the java based producer uses murmur2-32bit, but i don't see the need to use the same since various kafka clients seem not to stick a "default" hash function, e.g. the java based producer uses a different hash function than the scala based one.)

**Comment by datariot** [comment]
This is a requirement for some work I'm about to do. I new to Rust (coming from Java/Scala + Kafka background) but I could take a stab at this unless you're already working on it.

**Comment by xitep** [comment]
hello @datariot, it wasn't a priority for me right now, but i could give it precedence since the changes will have impact on other issues i planed to resolve. unfortunately, this will include some public api changes, though not as big as in the last 0.2 release.

**Comment by datariot** [comment]
I feel partitioning by key is a pretty important part of a scalable Kafka project, so if it's going to impact other things it might be good to prioritize. Also it would selfishly help me ;-)

**Comment by xitep** [comment]
@datariot i just pushed two very experimental commits to branch [consistent-partitioning](https://github.com/spicavigo/kafka-rust/commits/consistent-partitioning) allowing the partitioner to obtain the total partition count for a topic. this would allow you to implement consistent hashing in your own, custom partitioner. feel free to experiment with it. please note, this is really just a very first draft and i surely don't want to promise this API will be preserved (but it's going to be something like that.)

**Comment by xitep** [comment]
Hello @datariot,

so I took some the time to get this done. Can you review/try out branch [consistent-partitioning](https://github.com/spicavigo/kafka-rust/commits/consistent-partitioning)? I'd be greatly interested in feedback.

So far, I've chosen `SipHash` since that is part of the std library, so no extra dependencies are required. However, I managed to provide the possibility for a user to define a different hash implementation through the pubilc API of the `producer::DefaultPartitioner`. This can give us some time until we make a choice. So far I've looked, it seems `xxhash` might be a better alternative. (`fnv` is probably the fastest if one's keys are short - but that would be a bad default choice from our perspective, I think.) Do you have any opinions/suggestions on this?

Hope this works as expected. P.

**Comment by datariot** [comment]
Awesome @xitep! I'll try to set aside some time today or tomorrow to check this out.

**Comment by xitep** [comment]
@datariot have you had already a chance to play around with this so far? just curious.

**Comment by datariot** [comment]
@xitep yes, this is working as expected. I haven't put it under load so I don't have an idea on how SipHash performs. We usually partition on a String that is between 10-30 chars long.

**Comment by xitep** [comment]
@datariot many thanks for the confirmation. i'll merge the PR then. regarding SipHash i think it's fine enough as a default.

**Comment by xitep** [comment]
so it's in master now. however, in the end i decided to release it as part of 0.3.0, after implementing a few more issues. feel free to re-open in case of troubles. and many thanks so far.

**Comment by xitep** [comment]
Re-opening until this gets released with 0.3.0.

**Comment by xitep** [comment]
Closing this one; just released 0.3.0.
